import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(21, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(23, GPIO.OUT)
GPIO.setup(24, GPIO.OUT)
GPIO.setup(25, GPIO.OUT)
GPIO.setup(4, GPIO.OUT)
GPIO.setup(0, GPIO.OUT)
GPIO.setup(1, GPIO.OUT)
GPIO.setup(7, GPIO.OUT)
GPIO.setup(8, GPIO.OUT)
GPIO.setup(9, GPIO.OUT)
GPIO.setup(10, GPIO.OUT)
GPIO.setup(11, GPIO.OUT)

count=0 
while count < 30:
  count=count+1
  GPIO.output(17, GPIO.LOW)
  GPIO.output(18, GPIO.LOW)
  GPIO.output(21, GPIO.LOW)
  GPIO.output(22, GPIO.LOW)
  GPIO.output(23, GPIO.LOW)
  GPIO.output(24, GPIO.LOW)
  GPIO.output(25, GPIO.LOW)
  GPIO.output(4, GPIO.LOW)
  GPIO.output(7, GPIO.LOW)
  GPIO.output(8, GPIO.LOW)
  GPIO.output(9, GPIO.LOW)
  GPIO.output(10, GPIO.LOW)
  GPIO.output(11, GPIO.LOW)
  GPIO.output(0, GPIO.LOW)
  GPIO.output(1, GPIO.LOW)

  if count==1 or count==30: GPIO.output(17, GPIO.HIGH)
  if count==2 or count==29: GPIO.output(18, GPIO.HIGH)
  if count==3 or count==28: GPIO.output(21, GPIO.HIGH)
  if count==4 or count==27: GPIO.output(22, GPIO.HIGH)
  if count==5 or count==26: GPIO.output(23, GPIO.HIGH)
  if count==6 or count==25: GPIO.output(24, GPIO.HIGH)
  if count==7 or count==24: GPIO.output(25, GPIO.HIGH)
  if count==8 or count==23: GPIO.output(4, GPIO.HIGH)
  if count==9 or count==22: GPIO.output(7, GPIO.HIGH)
  if count==10 or count==21: GPIO.output(8, GPIO.HIGH)
  if count==11 or count==20: GPIO.output(9, GPIO.HIGH)
  if count==12 or count==19: GPIO.output(10, GPIO.HIGH)
  if count==13 or count==18: GPIO.output(11, GPIO.HIGH)
  if count==14 or count==17: GPIO.output(0, GPIO.HIGH)
  if count==15 or count==16: GPIO.output(1, GPIO.HIGH)
  time.sleep(.5)
 